//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int BatchId { get; set; }
        public string BatchName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> TentativeEndDate { get; set; }
        public Nullable<int> NoOfHours { get; set; }
        public int HoursTaken { get; set; }
        public string Remarks { get; set; }
    }
}
